import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Footer from "~/components/navigation/Footer";
import Header from "~/components/navigation/Header";
import Sidebar from "~/components/navigation/Sidebar";
import { useSteps } from "~/components/provider/StepsProvider";

const Home: NextPage = () => {
  const { getStepComponent, activeStep } = useSteps();
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="relative flex min-h-screen flex-col">
        <Header />
        <div className="mx-auto w-full flex-1 pb-36 pt-12 md:pt-0">
          {getStepComponent()}
        </div>
        {activeStep.id !== "loader" &&
          activeStep.id !== "result" &&
          activeStep.id !== "verification" && (
            <div className="fixed right-6 hidden h-screen items-center md:flex">
              <Sidebar />
            </div>
          )}
        <Footer />
      </main>
    </>
  );
};

export default Home;
